name: CI

on:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Dependencies
        run: curl -s https://raw.githubusercontent.com/Cloudbox/cb/develop/cb_install.sh | sudo -H bash; cd /srv/git/cloudbox
        
      - name: Import default configuration
        run: for i in defaults/*; do cp -n $i "$(basename "${i%.*}")"; done

      - name: Change default configuration user
        run: sed -i 's/seed/runner/g' accounts.yml

      - name: Syntax Check
        run: sudo ansible-playbook cloudbox.yml --syntax-check

      - name: Install Cloudbox
        run: sudo ansible-playbook cloudbox.yml --tags "cloudbox,emby,netdata,sabnzbd" --skip-tags "settings" --extra-vars '{"continuous_integration":true}'
