name: CI

on:
  workflow_dispatch:
  push:

jobs:
  install:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Dependencies
        run: curl -s https://raw.githubusercontent.com/Cloudbox/cb/develop/cb_install.sh | sudo -H bash; cd /srv/git/cloudbox
 
      - name: Chown /srv/git
        run: sudo chown -R runner:runner /srv/git
 
      - name: Import default configuration
        run: cd /srv/git/cloudbox && for i in defaults/*; do cp -n $i "$(basename "${i%.*}")"; done

      - name: Change default configuration user
        run: cd /srv/git/cloudbox && sed -i 's/seed/runner/g' accounts.yml

      - name: Syntax Check
        run: cd /srv/git/cloudbox && sudo ansible-playbook cloudbox.yml --syntax-check

      - name: Install Cloudbox
        run: cd /srv/git/cloudbox && sudo ansible-playbook cloudbox.yml --tags "cloudbox,emby,netdata,sabnzbd" --skip-tags "settings" --extra-vars '{"continuous_integration":true}'
        
      - name: Test cb
        run: sb install settings
